CREATE TABLE IF NOT EXISTS dbo.people (
	peopleId													INT  NOT NULL AUTO_INCREMENT,
	siteOwner													BOOLEAN				NOT NULL,
	twitter														VARCHAR(2083)			NULL,
	lastName													VARCHAR(500)			NULL,
	useShorthandDurations										BOOLEAN				NOT NULL,
	profile														VARCHAR(65535)			NULL,
	userUUID													VARCHAR(500)			NULL,
	userName													VARCHAR(500)			NULL,
	id															VARCHAR(100)		NOT NULL,
	phoneNumberOffice											VARCHAR(100)			NULL,
	lastActive													VARCHAR(40)				NULL,
	phoneNumberMobile											VARCHAR(100)			NULL,
	firstName													VARCHAR(100)			NULL,
	userType													VARCHAR(100)			NULL,
	imService													VARCHAR(500)			NULL,
	imHandle													VARCHAR(500)			NULL,
	loginCount													VARCHAR(100)			NULL,
	openId														VARCHAR(100)			NULL,
	phoneNumberOfficeExt										VARCHAR(100)			NULL,
	twoFactorAuthEnabled										BOOLEAN				NOT NULL,
	hasAccessToNewProjects										BOOLEAN				NOT NULL,
	addressZip													VARCHAR(100)			NULL,
	phoneNumberFax												VARCHAR(40)				NULL,
	fullName													VARCHAR(500)			NULL,
	lastLogin													VARCHAR(40)				NULL,
	administrator												BOOLEAN				NOT NULL,
	addressCity													VARCHAR(500)			NULL,
	pid															VARCHAR(500)			NULL,
	profileText													VARCHAR(65535)			NULL,
	phoneNumberHome												VARCHAR(100)			NULL,
	emailAddress												VARCHAR(100)			NULL,
	lengthOfDay													VARCHAR(10)				NULL,
	companyName													VARCHAR(500)			NULL,
	lastChangedOn												VARCHAR(40)				NULL,
	deleted														BOOLEAN				NOT NULL,
	addressState												VARCHAR(100)			NULL,
	addressCountry												VARCHAR(100)			NULL,
	notes														VARCHAR(1000)			NULL,
	addressZipCode												VARCHAR(100)			NULL,
	addressCountryCode											VARCHAR(10)				NULL,
	addressLine1												VARCHAR(100)			NULL,
	addressLine2												VARCHAR(100)			NULL,
	createdAt													VARCHAR(40)				NULL,
	textFormat													VARCHAR(100)			NULL,
	userInvitedDate												VARCHAR(40)				NULL,
	avatarUrl													VARCHAR(2083)			NULL,
	inOwnerCompany												BOOLEAN				NOT NULL,
	userInvited													VARCHAR(100)			NULL,
	emailAlt1													VARCHAR(500)			NULL,
	emailAlt2													VARCHAR(500)			NULL,
	emailAlt3													VARCHAR(500)			NULL,
	title														VARCHAR(500)			NULL,
	password													VARCHAR(12)				NULL,
	canEditProject												BOOLEAN					NULL,
	companiesId													INT						NULL,
	CONSTRAINT PK_people PRIMARY KEY (peopleId),
	CONSTRAINT FK_people_companies FOREIGN KEY (companiesId) REFERENCES dbo.companies(companiesId),
	CONSTRAINT UN_peopleID UNIQUE(id)
);

CREATE INDEX idx_people_companies ON dbo.people(companiesId)
