CREATE TABLE IF NOT EXISTS dbo.tasks (
	tasksId									INT NOT NULL AUTO_INCREMENT,
	id										INT					NOT NULL,
	boardColumnId							INT						NULL,
	boardColumnName							VARCHAR(100)			NULL,
	boardColumnColor						VARCHAR(100)			NULL,
	cardId									INT						NULL,
	canComplete								BOOLEAN				NOT NULL,
	commentsCount							INT						NULL,
	completerFirstName						VARCHAR(100)			NULL,
	completerLastName						VARCHAR(100)			NULL,
	description								VARCHAR(65500)			NULL,
	hasReminders							BOOLEAN				NOT NULL,
	hasUnreadComments						BOOLEAN				NOT NULL,
	private									INT						NULL,
	content									VARCHAR(65500)			NULL,
	tasksOrder								INT						NULL,
	projectName								VARCHAR(500)			NULL,
	taskListName							VARCHAR(500)			NULL,
	taskListPrivate							BOOLEAN				NOT	NULL,
	taskListIsTemplate						BOOLEAN				NOT NULL,
	status									VARCHAR(100)			NULL,
	companyName								VARCHAR(500)			NULL,
	creatorFirstName						VARCHAR(100)			NULL,
	creatorLastName							VARCHAR(100)			NULL,
	updaterFirstName						VARCHAR(100)			NULL,
	updaterLastName							VARCHAR(100)			NULL,
	completed								BOOLEAN				NOT NULL,
	startDate								VARCHAR(40)				NULL,
	dueDateBase								VARCHAR(40)				NULL,
	dueDate									VARCHAR(40)				NULL,
	createdOn								VARCHAR(40)				NULL,
	lastChangeOn							VARCHAR(40)				NULL,
	position								INT						NULL,
	completedOn								VARCHAR(40)				NULL,
	estimatedMinutes						INT						NULL,
	priority								VARCHAR(100)			NULL,
	progress								INT						NULL,
	harvestEnabled							BOOLEAN					NULL,
	lockdownId								VARCHAR(100)			NULL,
	taskListLockdownId						VARCHAR(100)			NULL,
	hasDependencies							INT						NULL,
	hasPredecessors							INT						NULL,
	hasTickets								BOOLEAN					NULL,
	timeIsLogged							VARCHAR(100)			NULL,
	attachmentsCount						INT						NULL,
	responsiblePartyNames					VARCHAR(65500)			NULL,
	responsiblePartyType					VARCHAR(100)			NULL,
	responsiblePartyFirstName				VARCHAR(1000)			NULL,
	responsiblePartyLastName				VARCHAR(1000)			NULL,
	responsiblePartySummary					VARCHAR(200)			NULL,
	recorringFrequency						VARCHAR(100)			NULL,
	sequenceId								INT						NULL,
	canEdit									BOOLEAN				NOT NULL,
	viewEstimatedTime						BOOLEAN				NOT NULL,
	creatorAvatarUrl						VARCHAR(2083)			NULL,
	canLogTime								BOOLEAN				NOT NULL,
	commentFollowersSummary					VARCHAR(200)			NULL,
	changeFollowersSummary					VARCHAR(200)			NULL,
	projectsId								INT						NULL,
	taskListsId								INT						NULL,
	companiesId								INT						NULL,
	peopleCreatorId							INT						NULL,
	peopleUpdaterId							INT						NULL,
	peopleCompleterId						INT						NULL,
	parentTaskId							INT						NULL,
	CONSTRAINT PK_tasks PRIMARY KEY (tasksId),
	CONSTRAINT FK_tasks_projects FOREIGN KEY (projectsId) REFERENCES dbo.projects(projectsId),
	CONSTRAINT FK_tasks_companies FOREIGN KEY (companiesId) REFERENCES dbo.companies(companiesId),
	CONSTRAINT FK_tasks_peopleCreator FOREIGN KEY (peopleCreatorId) REFERENCES dbo.people(peopleId),
	CONSTRAINT FK_tasks_peopleUpdater FOREIGN KEY (peopleUpdaterId) REFERENCES dbo.people(peopleId),
	CONSTRAINT FK_tasks_peopleCompleter FOREIGN KEY (peopleCompleterId) REFERENCES dbo.people(peopleId),
	CONSTRAINT FK_tasks_tasks FOREIGN KEY (parentTaskId) REFERENCES dbo.tasks(tasksId),
	CONSTRAINT UN_tasksID UNIQUE(id)
);

CREATE INDEX idx_tasks_projects ON dbo.tasks(projectsId);
CREATE INDEX idx_tasks_companies ON dbo.tasks(companiesId);
CREATE INDEX idx_tasks_peopleCreator ON dbo.tasks(peopleCreatorId);
CREATE INDEX idx_tasks_peopleUpdater ON dbo.tasks(peopleUpdaterId);
CREATE INDEX idx_tasks_peopleCompleter ON dbo.tasks(peopleCompleterId);
CREATE INDEX idx_tasks_tasks ON dbo.tasks(parentTaskId);
