CREATE TABLE IF NOT EXISTS dbo.timeentries (
	timeEntriesId					INT NOT NULL AUTO_INCREMENT,
	canEdit							BOOLEAN				NULL,
	companyId						INT					NULL,
	companyName						VARCHAR(100)    	NULL,
	createdAt						VARCHAR(40)			NULL,
	date							VARCHAR(40)         NULL,
	dateUserPerspective				VARCHAR(40)			NULL,
	description						VARCHAR(65500)		NULL,
	hasStartTime					VARCHAR(40)			NULL,
	hours							VARCHAR(40)			NULL,
	hoursDecimal					NUMERIC(5,2)		NULL,
	id								VARCHAR(100)	NOT NULL,
	invoiceNo						VARCHAR(500)   		NULL,
	invoiceStatus					VARCHAR(100)		NULL,
	isBillable						CHAR(1)				NULL,
	isBilled						CHAR(1)				NULL,
	minutes							VARCHAR(100)		NULL,
	parentTaskId					VARCHAR(100)		NULL,
	parentTaskName					VARCHAR(1000)		NULL,
	projectsId						INT				NOT NULL,
	projectName						VARCHAR(500)		NULL,
	projectStatus					VARCHAR(100)		NULL,
	taskEstimatedTime				VARCHAR(100)		NULL,
	todoItemId						VARCHAR(100)		NULL,
	taskIsPrivate					CHAR(1)				NULL,
	taskIsSubTask					CHAR(1)				NULL,
	todoItemName					VARCHAR(1000)		NULL,
	todoListId						VARCHAR(100)		NULL,
	taskListId						INT					NULL,
	todoListName					VARCHAR(1000)		NULL,
	ticketId						VARCHAR(1000)		NULL,
	updatedDate						VARCHAR(40)			NULL,
	userDeleted						BOOLEAN				NULL,
	personFirstName					VARCHAR(100)		NULL,
	personId						INT					NULL,
	personLastName					VARCHAR(100)		NULL,
	CONSTRAINT PK_timeentries PRIMARY KEY (timeentriesid),
	CONSTRAINT FK_timeentries_projects FOREIGN KEY (projectsid) REFERENCES dbo.projects(projectsid),
	CONSTRAINT FK_timeentries_companies FOREIGN KEY (companyid) REFERENCES dbo.companies(companiesid),
	CONSTRAINT FK_timeentries_tasklist FOREIGN KEY (taskListid) REFERENCES dbo.taskLists(tasklistsId),
	CONSTRAINT FK_timeentries_people FOREIGN KEY (personId) REFERENCES dbo.people(peopleid),
	CONSTRAINT UN_timeentriesid UNIQUE(id)
);

CREATE INDEX idx_timeentries_projects ON dbo.timeentries(projectsid);
CREATE INDEX idx_timeentries_companies ON dbo.timeentries(companyid);
CREATE INDEX idx_timeentries_tasklist ON dbo.timeentries(tasklistid);
CREATE INDEX idx_timeentries_people ON dbo.timeentries(personid);
